[32mINFO    [0m integration.test_backup_ceph:test_backup_ceph.py:362 Deploying a new mysql cluster
[32mINFO    [0m juju.model:model.py:2284 Deploying local:mysql-1
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  another-mysql/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  another-mysql/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  another-mysql/0 [executing] maintenance: Installing MySQL
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  another-mysql/0 [executing] maintenance: Setting up cluster node
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  another-mysql/0 [idle] active: Primary
  s3-integrator/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  another-mysql/0 [idle] active: Primary
[32mINFO    [0m integration.test_backup_ceph:test_backup_ceph.py:381 Rotating all mysql credentials
[32mINFO    [0m integration.test_backup_ceph:test_backup_ceph.py:399 Syncing credentials
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  another-mysql/0 [idle] active: Primary
  s3-integrator/0 [idle] active: 
[32mINFO    [0m integration.test_backup_ceph:test_backup_ceph.py:413 Waiting for blocked application status with another cluster S3 repository
[32mINFO    [0m integration.test_backup_ceph:test_backup_ceph.py:421 Restoring backup_id='2025-10-22T03:32:27Z'
[32mINFO    [0m integration.test_backup_ceph:test_backup_ceph.py:426 Ensuring that the pre-backup inserted value exists in database, while post-backup inserted value does not
[32mINFO    [0m integration.test_backup_ceph:test_backup_ceph.py:439 Inserting value after restore
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.test_backup_ceph:test_backup_ceph.py:447 Ensuring that pre-backup and post-restore values exist in the database
[32mINFO    [0m integration.test_backup_ceph:test_backup_ceph.py:458 Waiting for blocked application status after restore
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.11   unsupported  03:45:33Z

App            Version          Status   Scale  Charm          Channel        Rev  Exposed  Message
another-mysql  8.0.42-0ubun...  blocked      1  mysql                           1  no       Move restored cluster to another S3 repository
mysql                           blocked      0  mysql                           0  no       Move restored cluster to another S3 repository
s3-integrator                   active       1  s3-integrator  latest/stable  145  no       

Unit              Workload  Agent      Machine  Public address  Ports           Message
another-mysql/0*  active    executing  6        10.227.43.77    3306,33060/tcp  Primary
s3-integrator/0*  active    idle       3        10.227.43.155                   

Machine  State    Address        Inst id        Base          AZ             Message
3        started  10.227.43.155  juju-571641-3  ubuntu@22.04  runnervmwhb2z  Running
6        started  10.227.43.77   juju-571641-6  ubuntu@22.04  runnervmwhb2z  Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-2: 03:26:43 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 03:26:43 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 03:28:10 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 03:28:10 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 03:28:19 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 03:28:19 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 03:31:26 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 03:31:26 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 03:32:07 ERROR unit.mysql/2.juju-log database-peers:0: Binlogs collector is enabled but not running
unit-mysql-2: 03:32:07 ERROR unit.mysql/2.juju-log database-peers:0: Binlogs collector will be restarted due to force_restart option
unit-mysql-2: 03:32:44 ERROR unit.mysql/2.juju-log database-peers:0: Binlogs collector is enabled but not running
unit-mysql-2: 03:32:44 ERROR unit.mysql/2.juju-log database-peers:0: Binlogs collector will be restarted due to force_restart option
machine-4: 03:35:34 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 03:35:34 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 03:35:43 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 03:35:43 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-6: 03:39:29 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-6: 03:39:29 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...
[32mINFO    [0m integration.test_backup_ceph:test_backup_ceph.py:134 Cleaning backups from cloud buckets