[32mINFO    [0m integration.high_availability.conftest:conftest.py:29 Clearing continuous writes
[32mINFO    [0m integration.high_availability.conftest:conftest.py:32 Starting continuous writes
[32mINFO    [0m integration.high_availability.test_upgrade:test_upgrade.py:120 Get leader unit
[32mINFO    [0m integration.high_availability.test_upgrade:test_upgrade.py:125 Run pre-upgrade-check action
[32mINFO    [0m integration.high_availability.test_upgrade:test_upgrade.py:131 Inject dependency fault
[32mINFO    [0m integration.high_availability.test_upgrade:test_upgrade.py:136 Refresh the charm
[32mINFO    [0m integration.high_availability.test_upgrade:test_upgrade.py:139 Wait for upgrade to fail on leader
[32mINFO    [0m integration.high_availability.test_upgrade:test_upgrade.py:145 Ensure continuous_writes while in failure state
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:342 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:483 Retrieving primary unit
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=385 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=385 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=385 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=1217 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=1223 on unit mysql/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=1230 on unit mysql/2
[32mINFO    [0m integration.high_availability.test_upgrade:test_upgrade.py:148 Re-run pre-upgrade-check action
[32mINFO    [0m integration.high_availability.test_upgrade:test_upgrade.py:151 Re-refresh the charm
[32mINFO    [0m integration.high_availability.test_upgrade:test_upgrade.py:153 Wait for upgrade to start
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] blocked: ready to rollback application
  mysql/1 [idle] waiting: other units upgrading first...
  mysql/2 [idle] waiting: other units upgrading first...
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] waiting: other units upgrading first...
  mysql/1 [idle] waiting: other units upgrading first...
  mysql/2 [executing] maintenance: starting services...
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] waiting: other units upgrading first...
  mysql/1 [executing] maintenance: starting services...
  mysql/2 [idle] maintenance: upgrade completed
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [executing] active: 
  mysql/1 [executing] active: 
  mysql/2 [executing] active: 
[32mINFO    [0m integration.high_availability.test_upgrade:test_upgrade.py:160 Ensure continuous_writes after rollback procedure
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:342 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:483 Retrieving primary unit
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=7650 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=7650 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=7650 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=8555 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=8561 on unit mysql/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=8567 on unit mysql/2
[32mINFO    [0m integration.high_availability.conftest:conftest.py:37 Clearing continuous writes
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.9    unsupported  01:59:05Z

App             Version          Status  Scale  Charm           Channel      Rev  Exposed  Message
mysql           8.0.42-0ubun...  active      3  mysql                          2  no       
mysql-test-app  0.0.2            active      1  mysql-test-app  latest/edge   85  no       

Unit               Workload  Agent      Machine  Public address  Ports           Message
mysql-test-app/0*  active    idle       0        10.168.138.132                  
mysql/0*           active    idle       1        10.168.138.164  3306,33060/tcp  
mysql/1            active    executing  2        10.168.138.34   3306,33060/tcp  Primary
mysql/2            active    executing  3        10.168.138.7    3306,33060/tcp  

Machine  State    Address         Inst id        Base          AZ             Message
0        started  10.168.138.132  juju-7b3c80-0  ubuntu@22.04  runnervmf4ws1  Running
1        started  10.168.138.164  juju-7b3c80-1  ubuntu@22.04  runnervmf4ws1  Running
2        started  10.168.138.34   juju-7b3c80-2  ubuntu@22.04  runnervmf4ws1  Running
3        started  10.168.138.7    juju-7b3c80-3  ubuntu@22.04  runnervmf4ws1  Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-1: 01:45:19 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:45:19 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:45:19 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:47:15 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:47:15 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 01:47:15 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:47:23 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:47:23 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 01:47:24 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:47:45 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:47:45 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-0: 01:47:45 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-0: 01:55:38 ERROR unit.mysql/0.juju-log charms.data_platform_libs.v0.upgrade.VersionError - {'message': 'Versions incompatible, charm 1 can not be upgraded to 2', 'cause': 'Upgrades only supported for specific versions, charm versions satisfying requirement >1', 'resolution': ''}
unit-mysql-0: 01:55:38 CRITICAL unit.mysql/0.juju-log Upgrade failed, follow the instructions below to rollback:
    1. Re-run `pre-upgrade-check` action on the leader unit to enter 'recovery' state
    2. Run `juju refresh` to the previously deployed charm revision or local charm file

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...