[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m pytest_operator.plugin:plugin.py:734 Connecting to existing model concierge-lxd:testing on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHSession received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHTunneler received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m integration.high_availability.conftest:conftest.py:48 Deploying mysql and scaling to 3 units
[32mINFO    [0m juju.model:model.py:2284 Deploying local:mysql-0
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [allocating] waiting: waiting for machine
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [allocating] waiting: waiting for machine
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [allocating] waiting: waiting for machine
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [allocating] waiting: waiting for machine
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [executing] maintenance: Installing MySQL
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [executing] waiting: Waiting to start MySQL
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [executing] active: Primary
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [executing] maintenance: Installing MySQL
  mysql/2 [executing] maintenance: Installing MySQL
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [executing] maintenance: Setting up cluster node
  mysql/1 [executing] active: Primary
  mysql/2 [executing] waiting: Waiting to join the cluster
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [executing] maintenance: joining the cluster
  mysql/1 [idle] active: Primary
  mysql/2 [executing] waiting: waiting to join the cluster.
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/2 [executing] active: 
[32mINFO    [0m integration.high_availability.conftest:conftest.py:51 Deploying mysql-test-app
[32mINFO    [0m juju.model:model.py:2284 Deploying ch:amd64/jammy/mysql-test-app-85
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-test-app/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-test-app/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-test-app/0 [allocating] waiting: waiting for machine
[32mINFO    [0m integration.high_availability.conftest:conftest.py:54 Relating mysql with mysql-test-app
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] active: 
  mysql/1 [idle] active: Primary
  mysql/2 [idle] active: 
  mysql-test-app/0 [idle] waiting: 
[32mINFO    [0m integration.high_availability.conftest:conftest.py:29 Clearing continuous writes
[32mINFO    [0m integration.high_availability.conftest:conftest.py:32 Starting continuous writes
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:342 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=14 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=34 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=34 on unit mysql/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=53 on unit mysql/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=53 on unit mysql/2
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=73 on unit mysql/2
[32mINFO    [0m integration.high_availability.test_self_healing_restart_forceful:test_self_healing_restart_forceful.py:53 Stopping server on unit mysql/1
[32mINFO    [0m integration.high_availability.test_self_healing_restart_forceful:test_self_healing_restart_forceful.py:56 Removing data directory
[32mINFO    [0m integration.high_availability.test_self_healing_restart_forceful:test_self_healing_restart_forceful.py:72 Purge binlogs on unit mysql/0
[32mINFO    [0m integration.high_availability.test_self_healing_restart_forceful:test_self_healing_restart_forceful.py:72 Purge binlogs on unit mysql/2
[32mINFO    [0m integration.high_availability.test_self_healing_restart_forceful:test_self_healing_restart_forceful.py:80 Waiting unit to enter in maintenance.
[32mINFO    [0m integration.high_availability.test_self_healing_restart_forceful:test_self_healing_restart_forceful.py:87 Waiting unit to be back online.
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.high_availability.test_self_healing_restart_forceful:test_self_healing_restart_forceful.py:99 Check if instance in cluster
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:342 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=93 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=113 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=113 on unit mysql/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=132 on unit mysql/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=133 on unit mysql/2
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.high_availability.conftest:conftest.py:37 Clearing continuous writes
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.9    unsupported  07:20:43Z

App             Version          Status  Scale  Charm           Channel      Rev  Exposed  Message
mysql           8.0.42-0ubun...  active      3  mysql                          0  no       
mysql-test-app  0.0.2            active      1  mysql-test-app  latest/edge   85  no       Last written value=120

Unit               Workload  Agent  Machine  Public address  Ports           Message
mysql-test-app/0*  active    idle   3        10.93.191.100                   Last written value=120
mysql/0            active    idle   0        10.93.191.224   3306,33060/tcp  
mysql/1*           active    idle   1        10.93.191.136   3306,33060/tcp  
mysql/2            active    idle   2        10.93.191.60    3306,33060/tcp  Primary

Machine  State    Address        Inst id        Base          AZ             Message
0        started  10.93.191.224  juju-fe51e9-0  ubuntu@22.04  runnervmwhb2z  Running
1        started  10.93.191.136  juju-fe51e9-1  ubuntu@22.04  runnervmwhb2z  Running
2        started  10.93.191.60   juju-fe51e9-2  ubuntu@22.04  runnervmwhb2z  Running
3        started  10.93.191.100  juju-fe51e9-3  ubuntu@22.04  runnervmwhb2z  Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-1: 07:12:27 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 07:12:27 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 07:12:27 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 07:13:54 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 07:13:54 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 07:13:54 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 07:14:03 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 07:14:03 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 07:14:03 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 07:17:37 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 07:17:37 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-0: 07:17:37 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-1: 07:19:13 ERROR unit.mysql/1.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/mysql_vm_helpers.py", line 796, in _run_mysqlsh_script
    output = subprocess.check_output(  # noqa: S603
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-fe51e9-1.lxd:33062', '--python', '-c', "shell.options.set('useWizards', False)\nprint('###')\ncluster = dba.get_cluster('test_cluster')\nprint(cluster.status({'extended': False}))"]' returned non-zero exit status 1.
unit-mysql-1: 07:19:13 ERROR unit.mysql/1.juju-log Failed to get cluster status for test_cluster
unit-mysql-1: 07:19:13 ERROR unit.mysql/1.juju-log Failed to get cluster members
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/relations/mysql_provider.py", line 165, in _update_endpoints
    rw_endpoints, ro_endpoints, _ = self.charm.get_cluster_endpoints(DB_RELATION_NAME)
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 889, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster topology")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster topology
unit-mysql-1: 07:19:29 ERROR unit.mysql/1.juju-log ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/snap/charmed-mysql/common/var/run/mysqld/mysqld.sock' (2)
unit-mysql-1: 07:19:29 ERROR unit.mysql/1.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-1: 07:19:39 ERROR unit.mysql/1.juju-log ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/snap/charmed-mysql/common/var/run/mysqld/mysqld.sock' (2)
unit-mysql-1: 07:19:39 ERROR unit.mysql/1.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-1: 07:19:50 ERROR unit.mysql/1.juju-log ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/snap/charmed-mysql/common/var/run/mysqld/mysqld.sock' (2)
unit-mysql-1: 07:19:50 ERROR unit.mysql/1.juju-log Failed to get member state: mysqld daemon is down

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...