[32mINFO    [0m integration.test_vm_reboot:test_vm_reboot.py:78 Rebooting mysql/0
[32mINFO    [0m integration.test_vm_reboot:test_vm_reboot.py:78 Rebooting mysql/1
[32mINFO    [0m integration.test_vm_reboot:test_vm_reboot.py:78 Rebooting mysql/2
[32mINFO    [0m integration.test_vm_reboot:test_vm_reboot.py:80 Sleep to allow juju status change
[32mINFO    [0m integration.test_vm_reboot:test_vm_reboot.py:82 Waiting for the application to become idle
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [executing] active: 
  mysql/1 [executing] active: 
  mysql/2 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] maintenance: offline
  mysql/1 [executing] maintenance: offline
  mysql/2 [executing] maintenance: offline
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] maintenance: offline
  mysql/1 [executing] maintenance: offline
  mysql/2 [idle] maintenance: offline
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] maintenance: offline
  mysql/1 [idle] active: Primary
  mysql/2 [idle] maintenance: offline
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] active: 
  mysql/1 [idle] active: Primary
  mysql/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.2    unsupported  01:40:23Z

App    Version          Status  Scale  Charm  Channel  Rev  Exposed  Message
mysql  8.0.41-0ubun...  active      3  mysql             0  no       

Unit      Workload  Agent  Machine  Public address  Ports           Message
mysql/0   active    idle   0        10.89.175.226                   
mysql/1*  active    idle   1        10.89.175.30    3306,33060/tcp  Primary
mysql/2   active    idle   2        10.89.175.194                   

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.89.175.226  juju-7c6312-0  ubuntu@22.04      Running
1        started  10.89.175.30   juju-7c6312-1  ubuntu@22.04      Running
2        started  10.89.175.194  juju-7c6312-2  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-1: 01:31:30 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:31:30 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 01:31:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:32:50 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:32:50 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:32:51 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:32:59 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:32:59 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 01:32:59 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-1: 01:38:31 ERROR unit.mysql/1.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/mysql_vm_helpers.py", line 761, in _run_mysqlsh_script
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-7c6312-1.lxd:33062', '--python', '-c', "shell.options.set('useWizards', False)\nprint('###')\nshell.connect_to_primary()\nprimary_address = shell.parse_uri(session.uri)['host']\nprint(f'<PRIMARY_ADDRESS>{primary_address}</PRIMARY_ADDRESS>')"]' returned non-zero exit status 1.

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...